 //Inband packet defines

`define MAXPAYLOAD		504
//`define PAD_VALUE		16'hDEAD

 //Packet line locations (16b wide)
//`define RD_HEADER1			8'd0
//`define RD_HEADER2			8'd1
//`define RD_TIMESTAMP1		8'd2
//`define RD_TIMESTAMP2		8'd3
//`define RD_LAST				8'd255

 // Final header component allignments
 // in 16b wide lines
 // Header1 bits
`define PAYLOAD_LEN	8:0
`define TAG			12:9
`define MBZ			15:13

 // Header2 bits
`define CHAN		4:0
`define RSSI		10:5
`define BURST_END	11
`define BURST_START	12
`define DROPPED		13
`define UNDERRUN	14
`define OVERRUN		15


// Channel buffer header fifo bits (64b wide)
// These arranged to simplify the masking logic
// of modifying certain fields

//generated by channel_buffer
`define CB_PAYLOAD_LEN	8:0		//9
`define CB_OVERRUN		9		//1	

//inputs
`define CB_CHAN			14:10	//5
`define CB_RSSI			20:15	//6
`define CB_TIMESTAMP	52:21	//32
`define CB_UNDERRUN		53		//1
`define CB_DROPPED		54		//1

//currently unused
`define CB_TAG			58:55	//4
`define CB_BURST_END	59		//1
`define CB_BURST_START	60		//1
`define CB_MBZ			63:61	//3

`define CB_NON_INPUTS	63:59	//unset header values
`define CB_NI_SIZE		28	

`define CB_PASSTHROUGH	63:10	//Everything non-generated
`define CB_PT_SIZE		54
